// <auto-generated />
using Cwiczenia10.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cwiczenia10.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240610163402_Add rowes")]
    partial class Addrowes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cwiczenia10.Model.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_acount");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("FK_role");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("phone");

                    b.HasKey("IdAccount");

                    b.HasIndex("IdRole");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            IdAccount = 1,
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            IdRole = 1,
                            LastName = "Doe",
                            Phone = "123456789"
                        },
                        new
                        {
                            IdAccount = 2,
                            Email = "alice.smith@gmail.com",
                            FirstName = "Alice",
                            IdRole = 2,
                            LastName = "Smith",
                            Phone = "987654321"
                        },
                        new
                        {
                            IdAccount = 3,
                            Email = "bob.brown@gmail.com",
                            FirstName = "Bob",
                            IdRole = 3,
                            LastName = "Brown",
                            Phone = "456789123"
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_categoru");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            IdCategory = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            IdCategory = 3,
                            Name = "Category 3"
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_product");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("ProductDepth")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("depth");

                    b.Property<decimal>("ProductHeight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<decimal>("ProductWidth")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("width");

                    b.HasKey("IdProduct");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            Name = "Product 1",
                            ProductDepth = 3.3m,
                            ProductHeight = 2.2m,
                            ProductWidth = 1.1m
                        },
                        new
                        {
                            IdProduct = 2,
                            Name = "Product 2",
                            ProductDepth = 1.4m,
                            ProductHeight = 3.4m,
                            ProductWidth = 2m
                        },
                        new
                        {
                            IdProduct = 3,
                            Name = "Product 3",
                            ProductDepth = 3.3m,
                            ProductHeight = 2.2m,
                            ProductWidth = 1.1m
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.ProductCategory", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("FK_product");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("FK_Category");

                    b.HasKey("IdProduct", "IdCategory");

                    b.HasIndex("IdCategory");

                    b.ToTable("Products_Categories");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            IdCategory = 1
                        },
                        new
                        {
                            IdProduct = 2,
                            IdCategory = 2
                        },
                        new
                        {
                            IdProduct = 3,
                            IdCategory = 3
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            IdRole = 2,
                            Name = "User"
                        },
                        new
                        {
                            IdRole = 3,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.ShoppingCard", b =>
                {
                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("FK_account");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("FK_product");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.HasKey("IdAccount", "IdProduct");

                    b.HasIndex("IdProduct");

                    b.ToTable("Shopping_Carts");

                    b.HasData(
                        new
                        {
                            IdAccount = 1,
                            IdProduct = 1,
                            Amount = 13
                        },
                        new
                        {
                            IdAccount = 2,
                            IdProduct = 3,
                            Amount = 2
                        },
                        new
                        {
                            IdAccount = 3,
                            IdProduct = 2,
                            Amount = 5
                        });
                });

            modelBuilder.Entity("Cwiczenia10.Model.Account", b =>
                {
                    b.HasOne("Cwiczenia10.Model.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cwiczenia10.Model.ProductCategory", b =>
                {
                    b.HasOne("Cwiczenia10.Model.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenia10.Model.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cwiczenia10.Model.ShoppingCard", b =>
                {
                    b.HasOne("Cwiczenia10.Model.Account", "Account")
                        .WithMany("ShoppingCards")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenia10.Model.Product", "Product")
                        .WithMany("ShoppingCards")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cwiczenia10.Model.Account", b =>
                {
                    b.Navigation("ShoppingCards");
                });

            modelBuilder.Entity("Cwiczenia10.Model.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Cwiczenia10.Model.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ShoppingCards");
                });

            modelBuilder.Entity("Cwiczenia10.Model.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
